### PR TITLE
Updated serialization of binding_test

### PR DESCRIPTION
**Pull request by mdiepart**
Hello,
binding_test.ttt have been updated to the most recent CoppeliaSim version.
Older version have been kept for legacy reasons under the file binding_test_older_versions.ttt

### CODE REVIEW

**Comment by dourouc05** [comment]
By chance, do you know when these incompatible changes occurred? (What version of V-REP? Since they renamed the project to CoppeliaRobotics? According to the release notes, that seems likely: https://www.coppeliarobotics.com/helpFiles/en/versionInfo.htm#coppeliaSim4.0.0)

If so, the old file should be named after that version, something like "binding_test_pre_4.ttt".

**Comment by mdiepart** [comment]
I actually downloaded the oldest version I could find on their website, opened the file with it and saved it. It was then possible to open the file with CoppeliaSim. 
It was impossible to open it with both CoppeliaSim v4.0.0 and V-Rep v3.6.2.
I will check what version was the first not working.

**Comment by mdiepart** [comment]
I found that V-Rep 3.6.1 was the first version displaying the error. 
The filename have been updated accordingly.

**Comment by dourouc05** [comment]
Great, thanks! Just one last thing: you're still having a `youbot/binding_test_older_versions.ttt` file.

**Comment by mdiepart** [comment]
Yes, my mistake. I deleted it. 
Thanks !

**Pull request merged**
